name: Build docs
on:
  release:
    types:
      - created

jobs:
  build_docs:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        poetry-version: [1.6.1]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Documentation build
        uses: johannes-huther/webhook.sh@v1.0.0
        with:
          webhook_url: ${{ secrets.DOC_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.DOC_TOKEN }}
      - name: API ref build
        uses: johannes-huther/webhook.sh@v1.0.0
        with:
          webhook_url: ${{ secrets.APIREF_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.APIREF_TOKEN }}